### ISSUE TITLE
i can't finde the payload generated

### ISSUE THREAD

**Issue by marcelo321** [Souhardya/Zerodoor#1]
1: /usr/bin/i686-w64-mingw32-gcc: not found
[*] Backdoor Generated now go infect lol ...[*]

i get that error... help pls

**Comment by Souhardya** [comment]
Hello :) first of all thanks for opening the issue :             Actually its best if you change usr/bin/i686-w64-mingw32-gcc path to your minigw compiler path  on your system ... I don't think the problem will persist more please kindly let me know if you get any other error

**Comment by Souhardya** [comment]
Usually you could try changing the path with only gcc :)

**Comment by marcelo321** [comment]
i am new in this, but can you help me with the commands?

**Comment by Souhardya** [comment]
No commands just change the  /usr/bin/i686-w64-mingw32-gcc ... to just gcc in zerodoor.py :)   it won't give no errors I guess

**Comment by Souhardya** [comment]
According to your distro please kindly change the gcc path you might get winsock not found error just use the exact path :) happy hacking

**Comment by unknownvision** [comment]
@Souhardya 
Hey, I'm having the same problem. 
I was looking forward to using it but ran into this error. Much like him, I'm new to Kali linux and Python.

I did as you told, to change it to just gcc but only ended up with. 

"Winshell.c:2:10: fatal error: winsock2.h: No such file or directory 
#include <winsock2.h>"

Did I do something wrong?
It would be much appreciated if you could help me fix this issue.

Thank you for your time :)

**Comment by Souhardya** [comment]
Hi :) 
It seems like winsock module isn't there 
I would recommend placing winsock.h compatible to your gcc on your system or otherwise you can choose to generate the payload on a Windows system
