### ISSUE TITLE
what wrong 

### ISSUE THREAD

**Issue by megamindAT** [Souhardya/Zerodoor#2]
Please specify the port :1234
Socket binding to port...
Connection established with192.168.1.86
<socket._socketobject object at 0x76b948b8>  // i'm print conn
Traceback (most recent call last):
  File "zerodoor.py", line 320, in <module>
    main()
  File "zerodoor.py", line 53, in main
    socket_connaccep()
  File "zerodoor.py", line 308, in socket_connaccep
    cmd_exe(conn)
NameError: global name 'cmd_exe' is not defined

**Comment by Souhardya** [comment]
Sorry for the delay this was an abandoned project so wasnt in the mood of updating but I have updated the code please try again :)
