### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by gbiagomba** [Souhardya/Zerodoor#3]
![image](https://user-images.githubusercontent.com/5851606/32067123-0e4d8404-ba50-11e7-8b40-c297e4ac763a.png)

I would recommend removing this. Because if someone actually uses your tool for "evil" and the victim traces it back to you. That message could lend you in a heap of legal trouble, my advise, take it off.

**Comment by Souhardya** [comment]
Done .. this project is old tho I was thinking to remove it but forget XD thanks for the suggestion

**Comment by gbiagomba** [comment]
@Souhardya my pleasure :) and if i may ask what that you move the project too? or did you just abandon it?
