### ISSUE TITLE
Error generating payload

### ISSUE THREAD

**Issue by d0ubl3puls4r** [Souhardya/Zerodoor#4]
Hello, after setting the value of lhost and lport to generate the executable, the following error message appears:

**winshell.c: In function ‘WinMain’:
winshell.c:24:37: warning: missing terminating " character
     hax.sin_port = htons(atoi("4444""));
                                     ^
winshell.c:24:37: error: missing terminating " character
     hax.sin_port = htons(atoi("4444""));
                                     ^~~~
winshell.c:25:5: error: expected ‘)’ before ‘hax’
     hax.sin_addr.s_addr = inet_addr(ip_addr);
     ^~~
winshell.c:32:1: error: expected ‘)’ before ‘}’ token
 }
 ^
winshell.c:32:1: error: expected ‘;’ before ‘}’ token
[*] Backdoor Generated now go infect lol ...[*]**

I wonder what this problem is? and its possible correction.
Thank you very much in advance

**Comment by juliourena** [comment]
It looks like you have an extra " in the port number.

**Comment by d0ubl3puls4r** [comment]
When I ran zerodoor I got the message:

**sh: 1: / usr / bin / i686-w64-mingw32-gcc: not found**

so I added the repository of kali 2.0 and installed mingw32 and then went to run zerodoor again, when it returned the error that I reported

Was that the whole problem?
I was not able to generate the payload without the mingw32 package that was not present in the current Kali Linux.

**Comment by Souhardya** [comment]
Hello :) first of all thanks for opening the issue : Actually its best if you manually change usr/bin/i686-w64-mingw32-gcc path to your minigw compiler path on your system in the code  ... I don't think the problem will persist more please kindly let me know if you get any other error

**Comment by Souhardya** [comment]
Thank you for pointing out the extra " I have updated the code if still the problem persists let me know :)

**Comment by Souhardya** [comment]
Currently I am closing the issue if problem persists reopen please regards
