### ISSUE TITLE
post operation commands

### ISSUE THREAD

**Issue by d0ubl3puls4r** [Souhardya/Zerodoor#6]
Hello, I would like to know once that I can access through the connection in zerodoor, what are the commands that can be executed already tried commands like ls, pwd, dir, but always the error, as I show below for example:

Please specify the port: 443
Binding socket to port: 443
Connection has been established | IP 192.168.0.33 | Port 49867
**dir**
Traceback (most recent call last):
  File "./zerodoor.py", line 328, in <module>
    main ()
  File "./zerodoor.py", line 53, in main
    socket_accept ()
  File "./zerodoor.py", line 311, in socket_accept
    send_commands (conn)
  File "./zerodoor.py", line 324, in send_commands
    client_response = str (conn.recv (1024), "utf-8")
TypeError: str () takes at most 1 argument (2 given)

I would like to know what may be wrong, if there are specific commands that can be executed, post-scan modules, etc ...

**Comment by Souhardya** [comment]
Indeed I see listener is quite a bit buggy but no worries I will take a keen look to fix the bugs ..

**Comment by Souhardya** [comment]
Please do check now if you still hit the error please notify me .. I haven't tested it yet but I am sure it's fixed ainfe I just had a silly mistake
