### ISSUE TITLE
javascript

### ISSUE THREAD

**Issue by emans841** [Souhardya/Zerodoor#8]
kindly show us how to use the javascript backdoor

**Comment by Souhardya** [comment]
Let's suppose you have a executable kind of backdoor hosted on your web server ex. malicious .exe ... When you use the JavaScript backdoor you will be prompted first for the payload URL in which you have to input your backdoor 's URL like www.example.com/malicious.exe then you will be prompted for custom process name in which you can use a process name like malicious ... Once you get the JavaScript file generated you execute on the victim's computer once executed it will download the malicious.exe from your web server into ℅TEMP% and execute it .... Hope this helps if you find it difficult please kindly reopen this issue I will help you :)
