### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa2 in position 24: ordinal not in range

### ISSUE THREAD

**Issue by gearcapitan** [Souhardya/Zerodoor#9]
![kali linux-2018-01-22-05-34-35](https://user-images.githubusercontent.com/13740942/35218904-f8e6924c-ff35-11e7-8fa7-bbb6bc4278b5.png)
the session dies before being created

**Comment by Souhardya** [comment]
Hi thanks for reporting the issue can you check now ? 

Please let me know kindly

**Comment by gearcapitan** [comment]
the problem persists
Do I need to install some prerequisite?

![kali linux-2018-01-22-13-28-02](https://user-images.githubusercontent.com/13740942/35240210-58048ff8-ff78-11e7-9382-62d761570859.png)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa2 in position 24: invalid start byte

**Comment by antonytuff** [comment]
[?] Enter your IP (LHOST): 192.168.1.13 
[?] Enter your port (LPORT):4444
sh: 1: /usr/bin/i686-w64-mingw32-gcc: not found
[*] Backdoor Generated now go infect lol ...[*]


Any Help

**Comment by Souhardya** [comment]
I will be looking at it :)

**Comment by Souhardya** [comment]
Listener replaced with default unix netcat :P 
Fuck sockets no problem should occur now
Reopen issue if you find any bug
